name: "Let's Act Busy"

on:
  schedule:
      - cron: '0 8 * * *'  # Schedule every morning at 8 o'clock

  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Git configuration
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "afri-bit"

    - name: Writing changes for commit
      shell: bash
      run: |
        #!/bin/bash

        # Get the current day using the date command
        current_day=$(date +"%A")
        text_file=${{ github.workspace }}/src/playground.txt

        echo "" >> $text_file

        # Check if the current day is Tuesday
        if [ "$current_day" == "Sunday" ]; then
            for ((index=0; index<10; index++))
            do
                echo -n "0" >> $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Monday" ]; then
            for ((index=0; index<7; index++))
            do
                echo -n "1" >> $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Tuesday" ]; then
            for ((index=0; index<4; index++))
            do
                echo -n "0" > $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Wednesday" ]; then
            for ((index=0; index<2; index++))
            do
                echo -n "1" >> $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Thursday" ]; then
            for ((index=0; index<4; index++))
            do
                echo -n "0" > $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Friday" ]; then
            for ((index=0; index<7; index++))
            do
                echo -n "1" > $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        elif [ "$current_day" == "Saturday" ]; then
            for ((index=0; index<10; index++))
            do
                echo -n "0" > $text_file
                git add .
                git commit -m "Automated commit on `date`"
            done
        else
            echo "Nothing to be done!"
        fi

    - name: Push Changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        branch: master
        github_token: ${{ secrets.GH_PAT }}